spring:
  application:
    name: spring-admin

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://spring-eureka:8761/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
